<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <EnableNativeDllCopy>true</EnableNativeDllCopy>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MudBlazor"/>
        <PackageReference Include="TUnit"/>
        <PackageReference Include="TUnit.Playwright"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\InfiniFrame.BlazorWebView\InfiniFrame.BlazorWebView.csproj" />
        <ProjectReference Include="..\InfiniFrameTests.Playwright\InfiniFrameTests.Playwright.csproj" />
        <ProjectReference Include="..\InfiniFrameTests.Shared\InfiniFrameTests.Shared.csproj" />
    </ItemGroup>
</Project>
