<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <EnableNativeDllCopy>true</EnableNativeDllCopy>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit"/>
        <PackageReference Include="TUnit.Playwright"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\InfiniFrame.BlazorWebView\InfiniFrame.BlazorWebView.csproj" />
        <ProjectReference Include="..\InfiniFrameTests.Playwright\InfiniFrameTests.Playwright.csproj" />
        <ProjectReference Include="..\InfiniFrameTests.Shared\InfiniFrameTests.Shared.csproj" />
    </ItemGroup>

    <Target Name="CopyWebRootToOutput"
            AfterTargets="Build"
            Condition="'$(DesignTimeBuild)'!='true' and '$(IsCrossTargetingBuild)'!='true'">
        <ItemGroup>
            <BlazorTestWebRootFiles Include="$(ProjectDir)wwwroot\**\*" />
        </ItemGroup>

        <Copy SourceFiles="@(BlazorTestWebRootFiles)"
              DestinationFiles="@(BlazorTestWebRootFiles->'$(TargetDir)wwwroot\%(RecursiveDir)%(Filename)%(Extension)')"
              SkipUnchangedFiles="true" />
    </Target>

</Project>