<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('OSX'))">
            $(TargetFrameworks);
            net8.0-maccatalyst;
            net9.0-maccatalyst;
            net10.0-maccatalyst
        </TargetFrameworks>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="TUnit.Core"/>
        <PackageReference Include="NSubstitute" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\InfiniFrame.WebServer\InfiniFrame.WebServer.csproj"/>
        <ProjectReference Include="..\..\src\InfiniFrame\InfiniFrame.csproj"/>
        <ProjectReference Include="..\..\src\InfiniFrame.Shared\InfiniFrame.Shared.csproj"/>
    </ItemGroup>

</Project>
