<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <PackageId>InfiniLore.InfiniFrame.Server</PackageId>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfiniFrame\InfiniFrame.csproj" />
    </ItemGroup>

</Project>
