<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ApplicationIcon>../../assets/favicon.ico</ApplicationIcon>
        <GenerateTestingPlatformEntryPoint>false</GenerateTestingPlatformEntryPoint>
        <NoWarn>$(NoWarn);TUnit0034</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/InfiniFrame/InfiniFrame.csproj"/>
        <ProjectReference Include="../../src/InfiniFrame.Shared/InfiniFrame.Shared.csproj"/>
        <ProjectReference Include="../../src/InfiniFrame.BlazorWebView/InfiniFrame.BlazorWebView.csproj"/>
        <ProjectReference Include="../InfiniTests/InfiniTests.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="../../assets/favicon.ico">
            <Link>Assets/favicon.ico</Link>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="../TestHost/MacOsTestingPlatformEntryPoint.cs" Link="TestHost/MacOsTestingPlatformEntryPoint.cs"/>
    </ItemGroup>

</Project>
