<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <NoWarn>$(NoWarn);CS0105</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit"/>
        <PackageReference Include="TUnit.Mocks"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/InfiniFrame/InfiniFrame.csproj"/>
        <ProjectReference Include="../../src/InfiniFrame.Shared/InfiniFrame.Shared.csproj"/>
        <ProjectReference Include="../../src/InfiniFrame.BlazorWebView/InfiniFrame.BlazorWebView.csproj"/>
        <ProjectReference Include="../InfiniTests/InfiniTests.csproj"/>
    </ItemGroup>

</Project>
