<Project Sdk="Microsoft.NET.Sdk.Razor">
    <PropertyGroup>
        <ApplicationIcon>../../assets/favicon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MudBlazor"/>
        <PackageReference Include="TUnit"/>
        <PackageReference Include="TUnit.Playwright"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/InfiniFrame.BlazorWebView/InfiniFrame.BlazorWebView.csproj"/>
        <ProjectReference Include="../InfiniAutomationTests/InfiniAutomationTests.csproj"/>
        <ProjectReference Include="../InfiniTests/InfiniTests.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="../../assets/favicon.ico">
            <Link>Assets/favicon.ico</Link>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
</Project>
