<?xml version='1.0' encoding='utf-8'?>
<Project>
    <PropertyGroup Condition="'$(IsTestingPlatformApplication)' == 'true' and '$(InfiniFrameUseMacOsTestingPlatformHost)' == ''">
        <InfiniFrameUseMacOsTestingPlatformHost>true</InfiniFrameUseMacOsTestingPlatformHost>
    </PropertyGroup>

    <PropertyGroup Condition="'$(InfiniFrameUseMacOsTestingPlatformHost)' == 'true'">
        <GenerateTestingPlatformEntryPoint>false</GenerateTestingPlatformEntryPoint>
        <NoWarn>$(NoWarn);TUnit0034</NoWarn>
    </PropertyGroup>

    <ItemGroup Condition="'$(InfiniFrameUseMacOsTestingPlatformHost)' == 'true'">
        <Compile Include="$(MSBuildThisFileDirectory)TestHost/MacOsTestingPlatformEntryPoint.cs" Link="TestHost/MacOsTestingPlatformEntryPoint.cs"/>
    </ItemGroup>
</Project>
