<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>

        <PublishTrimmed>true</PublishTrimmed>
        <PublishAot>true</PublishAot>
        <SelfContained>true</SelfContained>
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-x64</RuntimeIdentifier>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\InfiniFrame\InfiniFrame.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="wwwroot\**\*.*"
                          LogicalName="$(AssemblyName).wwwroot.%(RecursiveDir)%(Filename)%(Extension)" />
    </ItemGroup>
</Project>
