<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>InfiniFrame</RootNamespace>
        <PackageId>InfiniLore.InfiniFrame.Shared</PackageId>
        <OutputType>Library</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="InfiniTests.InfiniFrame.Shared"/>
        <InternalsVisibleTo Include="InfiniTests.InfiniFrame"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        
        <PackageReference Include="JetBrains.Annotations"/>
        <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
        <PackageReference Include="Microsoft.Extensions.Options"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="../InfiniFrame.NativeBridge/InfiniFrame.NativeBridge.csproj">
          <ReferenceOutputAssembly>true</ReferenceOutputAssembly>
      </ProjectReference>
      <ProjectReference Include="..\InfiniFrame\InfiniFrame.csproj" />
    </ItemGroup>

</Project>
