<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>InfiniFrame</RootNamespace>
        <PackageId>InfiniLore.InfiniFrame.Shared</PackageId>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        
        <PackageReference Include="JetBrains.Annotations"/>
        <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
        <PackageReference Include="Microsoft.Extensions.Options"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\InfiniFrame.NativeBridge\InfiniFrame.NativeBridge.csproj" />
    </ItemGroup>

</Project>
