<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <PackageId>InfiniLore.InfiniFrame.Js</PackageId>
        <OutputType>Library</OutputType>

        <RunFrontendBuild Condition="'$(RunFrontendBuild)'==''">true</RunFrontendBuild>

        <FrontendOutputFile>$(ProjectDir)wwwroot/InfiniFrame.js</FrontendOutputFile>
        <FrontendStampFile>$(ProjectDir)obj\frontend-build.stamp</FrontendStampFile>
    </PropertyGroup>

    <ItemGroup>
        <Content Update="TypeScript/**/*"
                 Pack="false"
                 CopyToOutputDirectory="Never"
                 CopyToPublishDirectory="Never"
                 Visible="true"/>

        <Content Update="package.json"
                 Pack="false"
                 CopyToOutputDirectory="Never"
                 CopyToPublishDirectory="Never"
                 Visible="true"/>

        <Content Update="package-lock.json"
                 Pack="false"
                 CopyToOutputDirectory="Never"
                 CopyToPublishDirectory="Never"
                 Visible="true"/>

        <Content Update="tsconfig.json"
                 Pack="false"
                 CopyToOutputDirectory="Never"
                 CopyToPublishDirectory="Never"
                 Visible="true"/>

        <Content Update="vite.config.ts"
                 Pack="false"
                 CopyToOutputDirectory="Never"
                 CopyToPublishDirectory="Never"
                 Visible="true"/>

        <Content Update="vitest.config.ts"
                 Pack="false"
                 CopyToOutputDirectory="Never"
                 CopyToPublishDirectory="Never"
                 Visible="true"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="wwwroot\" />
    </ItemGroup>

    <Target Name="BuildFrontend"
            BeforeTargets="DispatchToInnerBuilds;Build;Pack"
            Condition="'$(DesignTimeBuild)'!='true'
                    and '$(RunFrontendBuild)'=='true'
                    and '$(SkipTypeScriptBuild)'!='true'">

        <Message Text="Running frontend build..." Importance="high" />

        <Exec
            Command="node &quot;$(ProjectDir)..\..\scripts\BuildFrontend.mjs&quot; &quot;$([System.String]::Copy('$(ProjectDir)').TrimEnd('\'))&quot; &quot;$(FrontendStampFile)&quot; &quot;$(FrontendOutputFile)&quot;"
            WorkingDirectory="$(ProjectDir)" />

        <PropertyGroup>
            <RunFrontendBuild>false</RunFrontendBuild>
        </PropertyGroup>

    </Target>

</Project>