<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <PackageId>InfiniLore.InfiniFrame.Js</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="InfiniFrame"/>
        <InternalsVisibleTo Include="InfiniFrame.WebServer"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="wwwroot/InfiniFrame.js"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(MSBuildThisFileDirectory)../InfiniFrame.Shared/InfiniFrame.Shared.csproj"/>
    </ItemGroup>

    <Target Name="BuildTypeScript" BeforeTargets="BeforeBuild" Condition="'$(SkipTypeScriptBuild)' != 'true'">
        <Exec Command="npm install" WorkingDirectory="$(MSBuildProjectDirectory)" />
        <Exec Command="npx webpack --env production=true" WorkingDirectory="$(MSBuildProjectDirectory)" />
    </Target>

    <Target Name="BuildTypeScriptForPack" BeforeTargets="Pack" Condition="'$(SkipTypeScriptBuild)' != 'true'">
        <Exec Command="npx webpack --env production=true" WorkingDirectory="$(MSBuildProjectDirectory)" />
    </Target>

</Project>
