<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <PackageId>InfiniLore.InfiniFrame.Js</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="InfiniFrame"/>
        <InternalsVisibleTo Include="InfiniFrame.WebServer"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="wwwroot/InfiniFrame.js"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfiniFrame.Shared\InfiniFrame.Shared.csproj"/>
    </ItemGroup>

</Project>
