<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="TUnit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\InfiniFrame.NativeBridge\InfiniFrame.NativeBridge.csproj"/>
        <ProjectReference Include="..\InfiniTests\InfiniTests.csproj"/>
    </ItemGroup>

</Project>
