<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <NoWarn>$(NoWarn);NU1902</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="bUnit"/>
        <PackageReference Include="TUnit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/InfiniFrame/InfiniFrame.csproj"/>
        <ProjectReference Include="../../src/InfiniFrame.Shared/InfiniFrame.Shared.csproj"/>
        <ProjectReference Include="../../src/InfiniFrame.Blazor/InfiniFrame.Blazor.csproj"/>
        <ProjectReference Include="../InfiniTests/InfiniTests.csproj"/>
    </ItemGroup>

</Project>
