<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <PackageId>InfiniLore.InfiniFrame</PackageId>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="InfiniFrameTests"/>
        <InternalsVisibleTo Include="InfiniFrameTests.Playwright"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions"/>
        <PackageReference Include="Microsoft.Extensions.FileProviders.Composite"/>
        <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded"/>
        <PackageReference Include="Microsoft.Extensions.FileProviders.Physical"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Console"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(MSBuildThisFileDirectory)../InfiniFrame.Js/InfiniFrame.Js.csproj"/>
        <ProjectReference Include="$(MSBuildThisFileDirectory)../InfiniFrame.Shared/InfiniFrame.Shared.csproj"/>
    </ItemGroup>

</Project>
