<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <InfiniFramePackAfterBuild>true</InfiniFramePackAfterBuild>
        <InfiniFramePackRid>auto</InfiniFramePackRid>
        <InfiniFramePackSelfContained>true</InfiniFramePackSelfContained>
        <InfiniFramePackCommand Condition="'$(InfiniFramePackCommand)'==''">infiniframe-pack</InfiniFramePackCommand>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\InfiniFrame\InfiniFrame.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="bin\$(Configuration)\net10.0\**\publish\InfiniFrameExample.SingleFileExe.exe"
              Visible="true">
            <Link>builds\$(Configuration)\InfiniFrameExample.SingleFileExe.exe</Link>
        </None>
    </ItemGroup>

    <Target Name="InfiniFramePackAfterBuild"
            AfterTargets="Build"
            Condition="'$(InfiniFramePackAfterBuild)'=='true' and '$(PublishSingleFile)'!='true' and '$(InfiniFramePackInvoked)'!='true'">
        <Exec Command="$(InfiniFramePackCommand) publish &quot;$(MSBuildProjectFullPath)&quot; --rid $(InfiniFramePackRid) --configuration $(Configuration) --framework $(TargetFramework) --self-contained $(InfiniFramePackSelfContained)" />
    </Target>
</Project>
