<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="TUnit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\InfiniFrame.Js\InfiniFrame.Js.csproj" />
      <ProjectReference Include="..\InfiniTests\InfiniTests.csproj" />
    </ItemGroup>

</Project>
