<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="../../src/InfiniFrame.Blazor/InfiniFrame.Blazor.csproj" />
        <ProjectReference Include="../../src/InfiniFrame.WebServer/InfiniFrame.WebServer.csproj" />
        <ProjectReference Include="..\..\src\InfiniFrame.BlazorWebView\InfiniFrame.BlazorWebView.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Update="wwwroot/**">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MudBlazor" />
        <PackageReference Include="Serilog"/>
        <PackageReference Include="Serilog.AspNetCore"/>
        <PackageReference Include="Serilog.Sinks.Async"/>
        <PackageReference Include="Serilog.Sinks.Console"/>
    </ItemGroup>
    <ItemGroup>
        <None Include="bin/$(Configuration)/$(TargetFramework)/**/publish/$(AssemblyName).exe;
                       bin/$(Configuration)/$(TargetFramework)/**/publish/$(AssemblyName)"
              Visible="true">
            <Link>builds/$(Configuration)/$(TargetFramework)/%(RecursiveDir)%(Filename)%(Extension)</Link>
        </None>
        <None Include="wwwroot\index.html" />
    </ItemGroup>

</Project>
