<Project Sdk="Microsoft.NET.Sdk.Razor">
    <PropertyGroup>
        <PackageId>InfiniLore.InfiniFrame.Blazor</PackageId>
        <OutputType>Library</OutputType>
        <Description>Pre-built Razor components for custom window chrome in InfiniFrame Blazor applications. Includes drag areas, window buttons, and resize thumbs.</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="$(MSBuildThisFileDirectory)../InfiniFrame/InfiniFrame.csproj"/>
        <ProjectReference Include="$(MSBuildThisFileDirectory)../InfiniFrame.Shared/InfiniFrame.Shared.csproj"/>
    </ItemGroup>

</Project>
