<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>InfiniLore.InfiniFrame.BlazorWebView</PackageId>
        <OutputType>Library</OutputType>
        <Description>Integrates a full Blazor WebAssembly-style application into a native InfiniFrame window with no HTTP server required. The Blazor runtime runs entirely in-process.</Description>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="InfiniTests.InfiniFrame.BlazorWebView"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebView"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="$(MSBuildThisFileDirectory)../InfiniFrame/InfiniFrame.csproj"/>
        <ProjectReference Include="$(MSBuildThisFileDirectory)../InfiniFrame.Blazor/InfiniFrame.Blazor.csproj"/>
        <ProjectReference Include="../InfiniFrame.Shared/InfiniFrame.Shared.csproj"/>
    </ItemGroup>

</Project>
