<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>InfiniLore.InfiniFrame.BlazorWebView</PackageId>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebView"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(MSBuildThisFileDirectory)../InfiniFrame/InfiniFrame.csproj"/>
        <ProjectReference Include="..\InfiniFrame.Blazor\InfiniFrame.Blazor.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="InfiniFrameTests.BlazorWebView"/>
    </ItemGroup>

</Project>
