<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <PackageId>InfiniLore.InfiniFrame.WebServer</PackageId>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfiniFrame\InfiniFrame.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Polyfill">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

</Project>
