<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>InfiniLore.InfiniFrame.WebServer</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.AspNetCore.Builder"/>
        <Using Include="Microsoft.AspNetCore.Hosting"/>
        <Using Include="Microsoft.AspNetCore.Hosting.Server"/>
        <Using Include="Microsoft.AspNetCore.Http"/>
        <Using Include="Microsoft.Extensions.DependencyInjection"/>
        <Using Include="Microsoft.Extensions.Hosting"/>
        <Using Include="Microsoft.Extensions.Logging"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(MSBuildThisFileDirectory)../InfiniFrame/InfiniFrame.csproj"/>
    </ItemGroup>

</Project>
