<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>InfiniLore.InfiniFrame.NativeBridge</PackageId>
        <OutputType>Library</OutputType>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Microsoft.Web.WebView2"
                          Condition="$([MSBuild]::IsOSPlatform('Windows'))"
                          PrivateAssets="all"
                          ExcludeAssets="all" />
        <PackageReference Include="Microsoft.Windows.ImplementationLibrary"
                          Condition="$([MSBuild]::IsOSPlatform('Windows'))"
                          PrivateAssets="all"
                          ExcludeAssets="all" />
    </ItemGroup>

    <Import Project="InfiniFrame.NativeBridge.Native.targets" />

</Project>
