<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <WebAppFrontendName>Vue</WebAppFrontendName>
        <WebAppFrontendDirectory>$(ProjectDir)Sources/infiniframe-playwright-vue</WebAppFrontendDirectory>
    </PropertyGroup>

    <Import Project="../InfiniAutomationTests.WebApp/InfiniAutomationTests.WebApp.targets"/>
</Project>
