<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="TUnit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../InfiniTests/InfiniTests.csproj"/>
        <ProjectReference Include="../../src/InfiniFrame.SingleFile/InfiniFrame.SingleFile.csproj"/>
    </ItemGroup>
</Project>
