<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <ApplicationIcon>wwwroot/favicon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/InfiniFrame/InfiniFrame.csproj"/>
        <ProjectReference Include="../../src/InfiniFrame.BlazorWebView/InfiniFrame.BlazorWebView.csproj"/>
        <ProjectReference Include="../../src/InfiniFrame.Blazor/InfiniFrame.Blazor.csproj"/>

        <ProjectReference Include="../../src/InfiniFrame.NativeBridge/InfiniFrame.NativeBridge.csproj">
            <ReferenceOutputAssembly>true</ReferenceOutputAssembly>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog"/>
        <PackageReference Include="Serilog.AspNetCore"/>
        <PackageReference Include="Serilog.Sinks.Async"/>
        <PackageReference Include="Serilog.Sinks.Console"/>
    </ItemGroup>

    <!--    <ItemGroup>-->
    <!--        <None Include="../../src/InfiniFrame.NativeBridge/Import.targets"-->
    <!--              Pack="true"-->
    <!--              PackagePath="build/InfiniFrame.targets"-->
    <!--              Visible="false" />-->
    <!--    </ItemGroup>-->
</Project>
