<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <UseAppHost>true</UseAppHost>
        <ApplicationIcon>wwwroot/favicon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/InfiniFrame/InfiniFrame.csproj"/>
        <ProjectReference Include="../../src/InfiniFrame.BlazorWebView/InfiniFrame.BlazorWebView.csproj"/>
        <ProjectReference Include="../../src/InfiniFrame.Blazor/InfiniFrame.Blazor.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog"/>
        <PackageReference Include="Serilog.AspNetCore"/>
        <PackageReference Include="Serilog.Sinks.Async"/>
        <PackageReference Include="Serilog.Sinks.Console"/>
    </ItemGroup>
</Project>
