<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <ApplicationIcon>wwwroot/favicon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\InfiniFrame\InfiniFrame.csproj" />
        <ProjectReference Include="..\..\src\InfiniFrame.BlazorWebView\InfiniFrame.BlazorWebView.csproj" />
        <ProjectReference Include="..\..\src\InfiniFrame.Blazor\InfiniFrame.Blazor.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Update="wwwroot\**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog"/>
        <PackageReference Include="Serilog.AspNetCore"/>
        <PackageReference Include="Serilog.Sinks.Async"/>
        <PackageReference Include="Serilog.Sinks.Console"/>
    </ItemGroup>
</Project>
