<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>InfiniLore.InfiniFrame.Application</PackageId>
        <Description>InfiniFrame application lifecycle and window orchestration.</Description>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="InfiniTests.InfiniFrame.Application" />
        <InternalsVisibleTo Include="InfiniTests.InfiniFrame.Window" />
        <InternalsVisibleTo Include="InfiniFrame.WebServer" />
        <InternalsVisibleTo Include="InfiniFrame.BlazorWebView" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <ProjectReference Include="../InfiniFrame.Shared/InfiniFrame.Shared.csproj" />
        <ProjectReference Include="../InfiniFrame.NativeBridge/InfiniFrame.NativeBridge.csproj" />
        <ProjectReference Include="../InfiniFrame.Window/InfiniFrame.Window.csproj" />
    </ItemGroup>
</Project>
