<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <LangVersion>14.0</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <ApplicationIcon>../../../assets/favicon.ico</ApplicationIcon>
        <FrontendDirectory>$(MSBuildProjectDirectory)/Source/InfiniFrame.Vue</FrontendDirectory>
        <FrontendLockFile>$(FrontendDirectory)/package-lock.json</FrontendLockFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../../src/InfiniFrame.WebServer/InfiniFrame.WebServer.csproj" />
        <ProjectReference Include="../../../src/InfiniFrame/InfiniFrame.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Update="wwwroot/**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Source/" />
    </ItemGroup>

    <Target Name="BuildFrontend" BeforeTargets="Build">
        <Message Text="Installing npm packages" Importance="high" />
        <Exec Condition="Exists('$(FrontendLockFile)')"
              Command="npm ci --include=dev"
              WorkingDirectory="$(FrontendDirectory)" />
        <Exec Condition="!Exists('$(FrontendLockFile)')"
              Command="npm install --include=dev"
              WorkingDirectory="$(FrontendDirectory)" />
        <Message Text="Building frontend with npm..." Importance="high" />
        <Exec Command="npm run vue.build" WorkingDirectory="$(FrontendDirectory)" />
    </Target>

    <Import Project="../../../InfiniFrame.NativeCopy.targets" />
</Project>
