<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <!--suppress MsbuildTargetFrameworkTagInspection -->
        <TargetFrameworks>net10.0</TargetFrameworks>
        <OutputType>Exe</OutputType>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>infiniframe-pack</ToolCommandName>
        <PackageId>InfiniLore.InfiniFrame.Tools.Pack</PackageId>
        <Description>Packaging tool for InfiniFrame single-file applications.</Description>
        <PackageTags>infiniframe;dotnet-tool;publish;single-file</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.CommandLine"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="InfiniTests.InfiniFrame.Tools.Pack"/>
    </ItemGroup>
</Project>
