<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <!--suppress MsbuildTargetFrameworkTagInspection -->
        <TargetFrameworks>net10.0</TargetFrameworks>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>infiniframe-pack</ToolCommandName>
        <PackageId>InfiniLore.InfiniFrame.Tools.Pack</PackageId>
        <Description>Single-command packaging tool for InfiniFrame apps.</Description>
        <PackageTags>infiniframe;dotnet-tool;publish;single-file</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.Sinks.Console" />
    </ItemGroup>

    <ItemGroup>
        <None Include="install-or-update-pack-tool.sh">
            <Pack>false</Pack>
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </None>
        <None Include="install-or-update-pack-tool.ps1">
            <Pack>false</Pack>
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="InfiniFrameTests.Tools.Pack"/>
    </ItemGroup>
</Project>
