<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ApplicationIcon>../../assets/favicon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="TUnit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/InfiniFrame/InfiniFrame.csproj"/>
        <ProjectReference Include="../../src/InfiniFrame.Shared/InfiniFrame.Shared.csproj"/>
        <ProjectReference Include="../../src/InfiniFrame.WebServer/InfiniFrame.WebServer.csproj"/>
        <ProjectReference Include="..\InfiniTests\InfiniTests.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="../../assets/favicon.ico">
            <Link>Assets/favicon.ico</Link>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
