<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <WebAppFrontendName>Angular</WebAppFrontendName>
        <WebAppFrontendDirectory>$(MSBuildProjectDirectory)</WebAppFrontendDirectory>
    </PropertyGroup>

    <Import Project="../InfiniAutomationTests.WebApp/InfiniAutomationTests.WebApp.targets"/>
</Project>
