name: infiniframe

services:
  linux-tests:
    image: infiniframe/testing-linux:latest
    build:
      context: ../..
      dockerfile: docker/linux-tests/Dockerfile
    working_dir: /work
    volumes:
      - ../../:/work/
    environment:
      - SOLUTION_FILTER=InfiniFrame.GitHubActions.Testing.slnf
      - CONFIGURATION=Release
      - NATIVE_PLATFORM=x64
      - USE_HOST_DISPLAY=${USE_HOST_DISPLAY:-0}
      - DISPLAY=${DISPLAY:-}
    entrypoint: ["/bin/bash", "-lc"]
    command:
      - "bash /work/scripts/nuget-install.sh && exec /usr/local/bin/tests.sh"
    stdin_open: true
    tty: true
  linux-playwright-tests:
    image: infiniframe/testing-linux:latest
    build:
      context: ../..
      dockerfile: docker/linux-tests/Dockerfile
    working_dir: /work
    volumes:
      - ../../:/work
    environment:
      - SOLUTION_FILTER=InfiniFrame.GitHubActions.Testing.Playwright.slnf
      - CONFIGURATION=Release
      - NATIVE_PLATFORM=x64
      - FRAMEWORKS=net8.0 net9.0 net10.0
      - USE_HOST_DISPLAY=${USE_HOST_DISPLAY:-0}
      - DISPLAY=${DISPLAY:-}
    entrypoint: ["/bin/bash", "-lc"]
    command:
      - "bash /work/scripts/nuget-install.sh && exec /usr/local/bin/playwright.sh"
    stdin_open: true
    tty: true
