<?xml version='1.0' encoding='utf-8'?>
<Project>
    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
        <LangVersion Condition="'$(TargetFramework)'=='net8.0'">12.0</LangVersion>
        <LangVersion Condition="'$(TargetFramework)'=='net9.0'">13.0</LangVersion>
        <LangVersion Condition="'$(TargetFramework)'=='net10.0'">14.0</LangVersion>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DebugType>embedded</DebugType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <Deterministic>true</Deterministic>
        <GeneratePackageOnBuild Condition="'$(GeneratePackageOnBuild)' == '' and '$(CI)' == 'true'">true</GeneratePackageOnBuild>
        <GeneratePackageOnBuild Condition="'$(GeneratePackageOnBuild)' == ''">false</GeneratePackageOnBuild>
        <IncludeBuildOutput>true</IncludeBuildOutput>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

        <Version>0.5.0</Version>
        <Authors>InfiniFrame, TryPhotino</Authors>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../LICENSE" Pack="true" PackagePath="" Visible="false" />
        <None Include="../../README.md" Pack="true" PackagePath="" Visible="false" />
        <None Include="../../assets/icon.png" Pack="true" PackagePath="" Visible="false" />
    </ItemGroup>
</Project>
