<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="TUnit"/>
        <PackageReference Include="NSubstitute"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\InfiniFrame.Shared\InfiniFrame.Shared.csproj"/>
        <ProjectReference Include="..\InfiniTests\InfiniTests.csproj"/>
    </ItemGroup>

</Project>
