<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="TUnit.Core"/>
        <PackageReference Include="TUnit.Playwright"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\InfiniFrame\InfiniFrame.csproj" />
        <ProjectReference Include="..\InfiniFrameTests.Shared\InfiniFrameTests.Shared.csproj" />
    </ItemGroup>
</Project>
