name: "CI: Release Docs"
on:
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write
    statuses: write
    checks: write

jobs:
    # noinspection UndefinedAction, UndefinedParamsPresent
    docs-validation:
        name: Validate Docs
        uses: ./.github/workflows/shared-testing-docs.yml
        with:
            target_sha: ${{ github.sha }}
        secrets: inherit
            
    # noinspection UndefinedAction, UndefinedParamsPresent
    deploy-docs:
        name: Publish Docs
        needs: docs-validation
        uses: ./.github/workflows/shared-release-docs.yml
        secrets: inherit
