name: "CI: Docs to GitHub Pages"
on:
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    # noinspection UndefinedAction, UndefinedParamsPresent
    deploy-docs:
        name: Build and Deploy Docs
        uses: ./.github/workflows/shared-release-docs.yml
        secrets: inherit
