#file: noinspection UndefinedAction,UndefinedParamsPresent
name: "CI: Full Test Suite"

permissions:
    contents: read
    statuses: write
    checks: write

on:
    push:
        branches:
            - core
        
    workflow_dispatch:
        inputs:
            pr_number:
                description: 'PR number to test. Leave empty to test the current branch commit.'
                required: false
                type: string
            with_coverage:
                description: 'Enable code coverage'
                type: boolean
                default: false
            run_windows:
                description: 'Run Windows GUI tests'
                type: boolean
                default: true
            run_windows_playwright:
                description: 'Run Windows Playwright tests'
                type: boolean
                default: true
            run_linux:
                description: 'Run Linux GUI tests'
                type: boolean
                default: true
            run_macos:
                description: 'Run macOS GUI tests'
                type: boolean
                default: true
            run_docs:
                description: 'Run docs validation'
                type: boolean
                default: true
            run_trim_aot:
                description: 'Run trim and NativeAOT compatibility validation'
                type: boolean
                default: true

concurrency:
    group: ${{ github.event_name == 'push' && github.ref == 'refs/heads/core' && format('core-{0}', github.workflow) || format('manual-{0}', github.run_id) }}
    cancel-in-progress: ${{ github.event_name == 'push' && github.ref == 'refs/heads/core' }}

jobs:
    python-tests:
        name: Python Tests
        uses: ./.github/workflows/shared-testing-python.yml

    run:
        name: Full Test Suite
        needs: python-tests
        uses: ./.github/workflows/shared-testing.yml
        with:
            pr_number: ${{ inputs.pr_number }}

            run_windows: ${{ github.event_name == 'push' || inputs.run_windows }}
            run_windows_playwright: ${{ github.event_name == 'push' || inputs.run_windows_playwright }}
            run_linux: ${{ github.event_name == 'push' || inputs.run_linux }}
            run_macos: ${{ github.event_name == 'push' || inputs.run_macos }}
            run_docs: ${{ github.event_name == 'push' || inputs.run_docs }}
            run_trim_aot: ${{ github.event_name == 'push' || inputs.run_trim_aot }}

            enable_test_exports: true
            enable_coverage: ${{ github.event_name == 'push' }}
        secrets: inherit

    coverage:
        name: Coverage Badges
        needs: [run]
        if: ${{ inputs.with_coverage }}
        uses: ./.github/workflows/shared-coverage.yml
        permissions:
            contents: write
