
name: Pending Check (Manual CI)

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    mark-pending:
        name: Mark PR as Pending
        runs-on: ubuntu-latest
        permissions:
            checks: write  # Changed from statuses to checks
        
        steps:
            -   name: Skip previous pending and mark current as pending
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    echo "Processing PR #${{ github.event.pull_request.number }}"
                    
                    # Get all commits in this specific PR
                    PR_COMMITS=$(curl -s \
                      -H "Authorization: Bearer $GITHUB_TOKEN" \
                      -H "Accept: application/vnd.github+json" \
                      "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits" \
                      | jq -r '.[].sha')
                    
                    # Process each commit in the PR (except the current one)
                    for commit in $PR_COMMITS; do
                      if [ "$commit" != "${{ github.event.pull_request.head.sha }}" ]; then
                        echo "Checking for pending check runs on commit: $commit"
                    
                        # Get check runs for this commit
                        PENDING_RUNS=$(curl -s \
                          -H "Authorization: Bearer $GITHUB_TOKEN" \
                          -H "Accept: application/vnd.github+json" \
                          "https://api.github.com/repos/${{ github.repository }}/commits/$commit/check-runs?check_name=Manual%20MultiPlatform%20CI" \
                          | jq -r '.check_runs[] | select(.status != "completed") | .id')
                    
                        for run_id in $PENDING_RUNS; do
                          if [ -n "$run_id" ] && [ "$run_id" != "null" ]; then
                            echo "Skipping check run ID: $run_id for commit $commit"
                            curl -s -X PATCH \
                              -H "Authorization: Bearer $GITHUB_TOKEN" \
                              -H "Accept: application/vnd.github+json" \
                              "https://api.github.com/repos/${{ github.repository }}/check-runs/$run_id" \
                              -d '{
                                "status": "completed",
                                "completed_at": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'",
                                "conclusion": "skipped",
                                "output": {
                                  "title": "Skipped",
                                  "summary": "Superseded by newer commit"
                                }
                              }' > /dev/null
                          fi
                        done
                      fi
                    done
                    
                    # Create pending check run for current commit
                    echo "Creating pending check run for current commit: ${{ github.event.pull_request.head.sha }}"
                    curl -X POST \
                      -H "Authorization: Bearer $GITHUB_TOKEN" \
                      -H "Accept: application/vnd.github+json" \
                      "https://api.github.com/repos/${{ github.repository }}/check-runs" \
                      -d '{
                        "name": "Manual MultiPlatform CI",
                        "head_sha": "${{ github.event.pull_request.head.sha }}",
                        "status": "queued",
                        "started_at": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'",
                        "output": {
                          "title": "Manual CI Pending",
                          "summary": "Waiting for manual trigger via workflow_dispatch."
                        }
                      }'