name: MultiPlatform Testing

on:
    workflow_dispatch:
        inputs:
            branch:
                description: 'Branch to run the tests on (default: master)'
                required: false
                default: 'master'
            pr_number:
                description: 'PR number to test (use the PR number from the URL)'
                required: false

jobs:
    mark-pending:
        name: Mark Manual CI as Pending
        runs-on: ubuntu-latest
        permissions:
            statuses: write
        steps:
            -   name: Set pending status
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    echo "Posting pending status for Manual MultiPlatform CI"
                    curl -X POST \
                      -H "Authorization: Bearer $GITHUB_TOKEN" \
                      -H "Accept: application/vnd.github+json" \
                      https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
                      -d '{"state":"pending","context":"Manual MultiPlatform CI","description":"Tests are running..."}'
    
    # ---------------------------------------------------------------------------------------
    # Linux (Full Desktop Environment)
    # ---------------------------------------------------------------------------------------
    linux-gui:
        needs: mark-pending
        name: Build & Test - Linux
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v5
                with:
                    ref: ${{ github.event.inputs.pr_number && format('refs/pull/{0}/merge', github.event.inputs.pr_number) || github.event.inputs.branch }}
            
            -   name: Setup .NET 9 SDK
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: '9.x'
            
            # Cache APT packages to avoid re-downloading
            -   name: Cache APT packages
                uses: actions/cache@v4
                with:
                    path: |
                        /var/cache/apt/archives
                        /var/lib/apt/lists
                    key: ${{ runner.os }}-apt-${{ hashFiles('**/onPullRequest-multiPlatformTesting.yml') }}
                    restore-keys: |
                        ${{ runner.os }}-apt-
            
            # Cache .NET packages
            -   name: Cache .NET packages
                uses: actions/cache@v4
                with:
                    path: ~/.nuget/packages
                    key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.props') }}
                    restore-keys: |
                        ${{ runner.os }}-nuget-
            
            # Cache .NET build output
            -   name: Cache .NET build
                uses: actions/cache@v4
                with:
                    path: |
                        **/bin
                        **/obj
                    key: ${{ runner.os }}-build-${{ hashFiles('**/*.cs', '**/*.csproj', '**/*.props') }}
                    restore-keys: |
                        ${{ runner.os }}-build-

            -   name: Install desktop environment and dependencies
                run: |
                    # Update package lists
                    sudo apt-get update
                    
                    export DEBIAN_FRONTEND=noninteractive
                    sudo apt-get install -y \
                        gnome-shell \
                        gnome-session \
                        gnome-settings-daemon \
                        mutter \
                        xvfb \
                        x11-utils \
                        x11-xserver-utils \
                        dbus-x11 \
                        at-spi2-core \
                        gsettings-desktop-schemas \
                        libnotify4 \
                        libwebkit2gtk-4.1-dev \
                        libgtk-3-dev \
                        libglib2.0-dev \
                        libgdk-pixbuf2.0-dev \
                        libpango1.0-dev \
                        libatk1.0-dev \
                        libharfbuzz-dev \
                        libepoxy-dev \
                        libx11-dev \
                        fonts-liberation \
                        xfonts-base

            -   name: Restore dependencies (cached)
                run: dotnet restore InfiniLore.Photino.GitHubActions.slnf

            -   name: Build (Release) (cached)
                run: dotnet build InfiniLore.Photino.GitHubActions.slnf --configuration Release --no-restore

            -   name: Start desktop environment and run tests
                run: |
                    echo "Starting desktop environment..."
                    
                    # Start D-Bus session (fixed syntax)
                    eval $(dbus-launch --sh-syntax)
                    
                    # Start Xvfb
                    Xvfb :99 \
                        -screen 0 1920x1080x24 \
                        -ac \
                        +extension GLX \
                        +extension RANDR \
                        +extension RENDER \
                        -nolisten tcp \
                        -noreset &
                    
                    export DISPLAY=:99
                    export XDG_RUNTIME_DIR="/tmp/runtime-$USER"
                    export XDG_SESSION_TYPE=x11
                    export XDG_SESSION_CLASS=user
                    export XDG_SESSION_DESKTOP=ubuntu
                    export XDG_CURRENT_DESKTOP=ubuntu:GNOME
                    export DESKTOP_SESSION=ubuntu
                    
                    # Create runtime directory
                    mkdir -p "$XDG_RUNTIME_DIR"
                    chmod 700 "$XDG_RUNTIME_DIR"
                    
                    # Wait for X server
                    echo "Waiting for X server..."
                    timeout 30 bash -c 'until xdpyinfo >/dev/null 2>&1; do sleep 1; done' || {
                        echo "X server failed to start"
                        exit 1
                    }
                    
                    # Start GNOME settings daemon
                    gnome-settings-daemon &
                    sleep 2
                    
                    # Start Mutter window manager
                    echo "Starting Mutter window manager..."
                    mutter --replace &
                    sleep 8
                    
                    # Verify setup
                    echo "=== Environment Status ==="
                    echo "Display: $DISPLAY"
                    echo "Desktop: $XDG_CURRENT_DESKTOP"
                    echo "Session: $XDG_SESSION_DESKTOP"
                    echo "D-Bus: $DBUS_SESSION_BUS_ADDRESS"
                    
                    echo "X11 info:"
                    xdpyinfo | head -3 || echo "xdpyinfo failed"
                    
                    echo "Window manager:"
                    ps aux | grep mutter | grep -v grep || echo "Mutter not found"
                    
                    # Test window capabilities
                    echo "Testing window manager capabilities..."
                    timeout 5 xwininfo -root >/dev/null 2>&1 && echo "✓ Window manager responding" || echo "✗ Window manager not responding"
                    
                    echo "=== Running Tests ==="
                    dotnet test InfiniLore.Photino.GitHubActions.slnf \
                        --configuration Release \
                        --no-build \
                        --no-restore \
                        --logger "console;verbosity=detailed"

    # ---------------------------------------------------------------------------------------
    # Windows
    # ---------------------------------------------------------------------------------------
    windows-gui:
        needs: mark-pending
        name: Build & Test - Windows
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
              with:
                  ref: ${{ github.event.inputs.pr_number && format('refs/pull/{0}/merge', github.event.inputs.pr_number) || github.event.inputs.branch }}

            - name: Setup .NET 9 SDK
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '9.x'

            - name: Restore dependencies
              run: dotnet restore InfiniLore.Photino.GitHubActions.slnf

            - name: Build (Release)
              run: |
                  dotnet build InfiniLore.Photino.GitHubActions.slnf `
                    --configuration Release `
                    --no-restore `
                    -p:GeneratePackageOnBuild=false `
                    -p:IsPackable=false

            - name: Run tests
              run: |
                  echo "Running tests on Windows..."
                  dotnet test InfiniLore.Photino.GitHubActions.slnf `
                    --configuration Release `
                    --no-build `
                    --no-restore `
                    --logger "console;verbosity=detailed"
                  
    update-status:
        name: Update Manual CI Status
        runs-on: ubuntu-latest
        needs: [ linux-gui, windows-gui ]
        permissions:
            statuses: write
        steps:
            -   name: Post final status
                if: ${{ always() }}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    if [[ "${{ needs.linux-gui.result }}" == "success" && "${{ needs.windows-gui.result }}" == "success" ]]; then
                      STATUS="success"
                      DESCRIPTION="MultiPlatform tests passed"
                    else
                      STATUS="failure"
                      DESCRIPTION="One or more platforms failed"
                    fi
                    
                    echo "Posting $STATUS to PR"
                    curl -X POST \
                      -H "Authorization: Bearer $GITHUB_TOKEN" \
                      -H "Accept: application/vnd.github+json" \
                      https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
                      -d "{\"state\":\"$STATUS\",\"context\":\"Manual MultiPlatform CI\",\"description\":\"$DESCRIPTION\"}"