name: DotNET Testing (Photino)

on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        branches: [ master ]

jobs:
    # ---------------------------------------------------------------------------------------
    # Linux (Headless)
    # ---------------------------------------------------------------------------------------
    linux-gui:
        name: Build & Test - Linux
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v5

            -   name: Setup .NET 9 SDK
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: '9.x'

            -   name: Install GUI dependencies and desktop environment
                run: |
                    sudo apt-get update
                    export DEBIAN_FRONTEND=noninteractive
                    sudo apt-get install -y \
                        xvfb \
                        x11-apps \
                        x11-xserver-utils \
                        xfonts-100dpi \
                        xfonts-75dpi \
                        xfonts-scalable \
                        xfonts-cyrillic \
                        metacity \
                        dbus-x11 \
                        at-spi2-core \
                        libnotify4 \
                        libwebkit2gtk-4.1-dev \
                        libgtk-3-dev \
                        libglib2.0-dev \
                        libgdk-pixbuf2.0-dev \
                        libpango1.0-dev \
                        libatk1.0-dev \
                        libharfbuzz-dev \
                        libepoxy-dev \
                        libx11-dev \
                        x11-utils

            -   name: Restore dependencies
                run: dotnet restore InfiniLore.Photino.GitHubActions.slnf

            -   name: Build (Release)
                run: dotnet build InfiniLore.Photino.GitHubActions.slnf --configuration Release --no-restore

            -   name: Start desktop environment and run tests
                run: |
                    echo "Starting virtual desktop environment with window manager..."
                    # Start D-Bus session
                    export $(dbus-launch)

                    # Start Xvfb with larger screen
                    Xvfb :99 -screen 0 1920x1080x24 -ac +extension GLX > /dev/null 2>&1 &
                    export DISPLAY=:99

                    # Start metacity window manager
                    metacity --replace > /dev/null 2>&1 &

                    # Wait for window manager to fully start
                    sleep 10

                    # Verify X server is working
                    xdpyinfo

                    # Run tests
                    echo "Running tests..."
                    dotnet test InfiniLore.Photino.GitHubActions.slnf \
                    --configuration Release \
                    --no-build \
                    --no-restore

    # ---------------------------------------------------------------------------------------
    # Windows
    # ---------------------------------------------------------------------------------------
    windows-test:
        name: Build & Test - Windows
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup .NET 9 SDK
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '9.x'

            - name: Restore dependencies
              run: dotnet restore InfiniLore.Photino.GitHubActions.slnf

            - name: Build (Release)
              run: |
                  dotnet build InfiniLore.Photino.GitHubActions.slnf `
                    --configuration Release `
                    --no-restore `
                    -p:GeneratePackageOnBuild=false `
                    -p:IsPackable=false

            - name: Run tests
              run: |
                  echo "Running tests on Windows..."
                  dotnet test InfiniLore.Photino.GitHubActions.slnf `
                    --configuration Release `
                    --no-build `
                    --no-restore `
                    --logger "console;verbosity=detailed"
