name: DotNET Testing (Photino)

on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        branches: [ master ]

jobs:
    test:
        name: Build & Test
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup .NET 9 SDK
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '9.x'
            
            # Install GTK and WebKit dependencies
            - name: Install WebKitGTK and dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y \
                    xvfb \
                    libwebkit2gtk-4.1-dev \
                    libgtk-3-dev \
                    libglib2.0-dev \
                    libgdk-pixbuf2.0-dev \
                    libpango1.0-dev \
                    libatk1.0-dev

            - name: Restore dependencies
              run: dotnet restore InfiniLore.Photino.GitHubActions.slnf

            - name: Build (Release)
              run: dotnet build InfiniLore.Photino.GitHubActions.slnf --configuration Release --no-restore -p:GeneratePackageOnBuild=false -p:IsPackable=false
            
            # Run tests inside a virtual display (required for Photino)
            - name: Run tests (headless)
              env:
                  CI: true
              run: |
                  xvfb-run -a dotnet test InfiniLore.Photino.GitHubActions.slnf \
                    --configuration Release \
                    --no-restore \
                    --no-build \
                    --logger "console;verbosity=normal" \
                    --logger "trx;LogFileName=test_results.trx"