name: Dotnet Testing

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        branches: [ core ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '9.x'

            - name: Restore dependencies
              run: dotnet restore InfiniLore.Photino.GitHubActions.slnf

            - name: Build
              run: dotnet build InfiniLore.Photino.GitHubActions.slnf --configuration Release --no-restore -p:GeneratePackageOnBuild=false -p:IsPackable=false

            - name: Run tests
              run: dotnet test InfiniLore.Photino.GitHubActions.slnf --configuration Release --no-restore --no-build
