name: DotNET Testing (Photino)

on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        branches: [ master ]

jobs:
    # ---------------------------------------------------------------------------------------
    # Linux (Headless)
    # ---------------------------------------------------------------------------------------
    linux-gui:
        name: Build & Test (Linux GUI)
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v5

            -   name: Setup .NET 9 SDK
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: '9.x'

            -   name: Install GUI dependencies
                run: |
                    sudo apt-get update
                    sudo apt-get install -y xvfb libnotify4 libwebkit2gtk-4.1-dev libgtk-3-dev \
                                            libglib2.0-dev libgdk-pixbuf2.0-dev libpango1.0-dev \
                                            libatk1.0-dev libharfbuzz-dev libepoxy-dev libx11-dev x11-utils

            -   name: Restore dependencies
                run: dotnet restore InfiniLore.Photino.GitHubActions.slnf

            -   name: Build (Release)
                run: dotnet build InfiniLore.Photino.GitHubActions.slnf --configuration Release --no-restore

            -   name: Run tests with virtual display
                run: |
                    echo "Running tests with xvfb..."
                    xvfb-run -a -s "-screen 0 1024x768x24" \
                    dotnet test InfiniLore.Photino.GitHubActions.slnf \
                    --configuration Release \
                    --no-build \
                    --no-restore

    # ---------------------------------------------------------------------------------------
    # Windows
    # ---------------------------------------------------------------------------------------
    windows-test:
        name: Build & Test (Photino - Windows)
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup .NET 9 SDK
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '9.x'

            - name: Restore dependencies
              run: dotnet restore InfiniLore.Photino.GitHubActions.slnf

            - name: Build (Release)
              run: |
                  dotnet build InfiniLore.Photino.GitHubActions.slnf `
                    --configuration Release `
                    --no-restore `
                    -p:GeneratePackageOnBuild=false `
                    -p:IsPackable=false

            - name: Run tests
              run: |
                  echo "Running tests on Windows..."
                  dotnet test InfiniLore.Photino.GitHubActions.slnf `
                    --configuration Release `
                    --no-build `
                    --no-restore `
                    --logger "console;verbosity=detailed"
