name: Pending Check (Manual CI)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
    mark-pending:
        name: Mark PR as Pending
        runs-on: ubuntu-latest
        permissions:
            statuses: write   # <-- allow posting commit statuses
        
        steps:
            -   name: Mark PR as pending
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    echo "Posting pending status for manual CI trigger"
                    curl -X POST \
                      -H "Authorization: Bearer $GITHUB_TOKEN" \
                      -H "Accept: application/vnd.github+json" \
                      https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
                      -d '{"state": "pending", "context": "Manual MultiPlatform CI", "description": "Waiting for manual trigger via workflow_dispatch."}'