name: DotNET Testing (Photino)

on:
    workflow_dispatch:
    pull_request:
        types: [ opened, synchronize, reopened, ready_for_review ]
        branches: [ master ]

jobs:
    # ---------------------------------------------------------------------------------------
    # Linux (Headless)
    # ---------------------------------------------------------------------------------------
    linux-gui:
        name: Build & Test - Linux
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v5

            -   name: Setup .NET 9 SDK
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: '9.x'

            -   name: Install full desktop environment
                run: |
                    sudo apt-get update
                    export DEBIAN_FRONTEND=noninteractive
                    sudo apt-get install -y \
                        ubuntu-desktop-minimal \
                        xvfb \
                        x11vnc \
                        gnome-session \
                        gnome-shell \
                        ubuntu-gnome-desktop \
                        dbus-x11 \
                        pulseaudio \
                        libnotify4 \
                        libwebkit2gtk-4.1-dev \
                        libgtk-3-dev \
                        libglib2.0-dev \
                        libgdk-pixbuf2.0-dev \
                        libpango1.0-dev \
                        libatk1.0-dev \
                        libharfbuzz-dev \
                        libepoxy-dev \
                        libx11-dev

            -   name: Restore dependencies
                run: dotnet restore InfiniLore.Photino.GitHubActions.slnf

            -   name: Build (Release)
                run: dotnet build InfiniLore.Photino.GitHubActions.slnf --configuration Release --no-restore

            -   name: Start full desktop session and run tests
                run: |
                    echo "Starting full GNOME desktop session..."

                    # Start D-Bus
                    sudo service dbus start
                    export $(dbus-launch)

                    # Start Xvfb with proper extensions
                    Xvfb :99 -screen 0 1920x1080x24 -ac +extension GLX +render -noreset &
                    export DISPLAY=:99

                    # Wait for X server
                    sleep 5

                    # Start GNOME session
                    gnome-session --session=ubuntu &

                    # Wait for desktop to fully load
                    sleep 15

                    # Verify desktop is running
                    ps aux | grep gnome

                    echo "Running tests with full desktop..."
                    dotnet test InfiniLore.Photino.GitHubActions.slnf \
                    --configuration Release \
                    --no-build \
                    --no-restore

    # ---------------------------------------------------------------------------------------
    # Windows
    # ---------------------------------------------------------------------------------------
    windows-test:
        name: Build & Test - Windows
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup .NET 9 SDK
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '9.x'

            - name: Restore dependencies
              run: dotnet restore InfiniLore.Photino.GitHubActions.slnf

            - name: Build (Release)
              run: |
                  dotnet build InfiniLore.Photino.GitHubActions.slnf `
                    --configuration Release `
                    --no-restore `
                    -p:GeneratePackageOnBuild=false `
                    -p:IsPackable=false

            - name: Run tests
              run: |
                  echo "Running tests on Windows..."
                  dotnet test InfiniLore.Photino.GitHubActions.slnf `
                    --configuration Release `
                    --no-build `
                    --no-restore `
                    --logger "console;verbosity=detailed"
