name: Publish Packages

on:
    workflow_dispatch:
    push:
        tags:
            - 'v*.*.*' # Match version tags like v1.0.0

jobs:   
    publish:
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.event.base_ref == 'refs/heads/master')
        
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v5
                
            -   name: Install Node.js
                uses: actions/setup-node@v5
                with:
                    node-version: '20'

            -   name: Install npm dependencies
                run: npm install

            -   name: Build JS bundle
                run: npm run production:build

            -   name: Setup .NET
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: '9.x'

            -   name: Restore dependencies
                run: dotnet restore InfiniLore.Photino.GitHubActions.slnf

            -   name: Build
                run: dotnet build InfiniLore.Photino.GitHubActions.slnf --configuration Release --no-restore
            
            # Ensure that the tests must pass 
            # The job will fail automatically if any test fails because `dotnet test` exits with a non-zero code
            -   name: Run tests
                run: dotnet test InfiniLore.Photino.GitHubActions.slnf --configuration Release --no-restore --no-build

            -   name: Publish to NuGet
                env:
                    NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
                run: |
                    dotnet nuget push src/InfiniLore.InfiniFrame.Blazor/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
                    dotnet nuget push src/InfiniLore.Photino.Js/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
                    dotnet nuget push src/InfiniLore.Photino.NET/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
                    dotnet nuget push src/InfiniLore.Photino.NET.Server/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
                    dotnet nuget push src/InfiniLore.Photino.Shared/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate

#            - name: Create GitHub Release
#              uses: softprops/action-gh-release@v2
#              with:
#                  generate_release_notes: true