#file: noinspection UndefinedAction,UndefinedParamsPresent
name: "Shared: release-bump-version"
on:
    workflow_call:
        inputs:
            version_bump:
                description: 'Version bump type'
                required: true
                type: string
            custom_version:
                description: 'Custom version (only used if "custom" is selected, e.g., 1.0.0 or 1.0.0-preview.1)'
                required: false
                type: string
                default: ''
        outputs:
            new_version:
                description: 'Calculated semantic version'
                value: ${{ jobs.bump-version.outputs.new_version }}
            tag_name:
                description: 'Created git tag name'
                value: ${{ jobs.bump-version.outputs.tag_name }}

jobs:
    bump-version:
        name: "CI: bump-version"
        runs-on: ubuntu-latest
        permissions:
            contents: write
        outputs:
            new_version: ${{ steps.bump.outputs.version }}
            tag_name: ${{ steps.bump.outputs.tag }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v7
                with:
                    fetch-depth: 0
                    token: ${{ secrets.RELEASE_TOKEN }}

            -   name: Bump Version
                id: bump
                uses: Code-Of-Chaos/action-version-bumper@v2.1.0
                with:
                    version_file: src/Directory.Build.props
                    additional_version_files: |
                        src/InfiniFrame.NativeBridge/Native/CMakeLists.txt
                        docs/package.json
                        src/InfiniFrame.Js/package.json
                        examples/WebApp/InfiniFrameExample.WebApp.Vue/Source/InfiniFrame.Vue/package.json
                        examples/WebApp/InfiniFrameExample.WebApp.React/Source/InfiniFrame.React/package.json
                        tests/InfiniAutomationTests.WebApp/package.json
                        tests/InfiniAutomationTests.WebApp.Angular/package.json
                        tests/InfiniAutomationTests.WebApp.React/package.json
                        tests/InfiniAutomationTests.WebApp.Vue/package.json
                    bump: ${{ inputs.version_bump }}
                    custom_version: ${{ inputs.custom_version }}
                    commit: 'true'
                    tag: 'true'
                    push: 'true'
                    floating_major_version: 'true'
                    floating_minor_version: 'true'
