#file: noinspection UndefinedAction,UndefinedParamsPresent
name: "Shared: Docs Tests"

on:
    workflow_call:
        inputs:
            checkout_ref:
                description: 'Git ref to checkout (optional)'
                type: string
                required: false
                default: ''
            target_sha:
                description: 'Commit SHA used for status/check updates'
                type: string
                required: true

permissions:
    contents: read
    statuses: write
    checks: write

jobs:
    docs-validation:
        name: CI Testing - Docs
        runs-on: ubuntu-latest
        env:
            TARGET_SHA: ${{ inputs.target_sha }}
        
        steps:
            -   name: Checkout
                uses: actions/checkout@v7
                with:
                    ref: ${{ inputs.checkout_ref != '' && inputs.checkout_ref || env.TARGET_SHA }}

            -   name: Setup Node
                uses: actions/setup-node@v7
                with:
                    node-version: 24
                    cache: npm
                    cache-dependency-path: |
                        docs/package-lock.json

            -   name: Install Docusaurus Dependencies
                shell: bash
                run: npm ci --prefix docs

            -   name: Build Docusaurus Docs
                shell: bash
                run: npm --prefix docs run build
