#file: noinspection UndefinedAction,UndefinedParamsPresent
name: "Shared: Python Tests"
permissions:
    contents: read
on:
    workflow_call:

jobs:
    python-tests:
        name: Python Tests
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v7

            -   name: Setup Python
                uses: actions/setup-python@v7
                with:
                    python-version: '3.x'

            -   name: Install Test Deps
                run: |
                    python -m pip install --upgrade pip
                    python -m pip install pytest

            -   name: Run Pytest
                run: python -m pytest .github/scripts -q

            -   name: Run Validations
                run: |
                    python .github/scripts/validate_package_id_prefix.py \
                      --slnf InfiniFrame.GitHubActions.Release.slnf \
                      --prefix InfiniLore